This scripts aims to make some adjustments of crispresso analysisi scripts to make it PE-compatible.  

Kexin Dong
Create: Sep 8, 2025

In [2]:
# check the length of input protospacer
import pandas as pd
import numpy as np

In [6]:
EA_LIB = pd.read_csv('/Users/kexindong/Documents/GitHub/PhD-FSR-MH-Lab/06_EA_screen_analysis/STEP3_generate_config_file/pegRNA_library_EA_LUAD_column_renamed.csv')
EA_LIB_BC_16NT = pd.read_csv('/Users/kexindong/Documents/GitHub/PhD-FSR-MH-Lab/06_EA_screen_analysis/STEP3_generate_config_file/pegRNA_library_EA_LUAD_column_renamed_bc_16nt.csv')

In [9]:
EA_LIB['indel_size'].value_counts()

indel_size
0     27919
1      1318
3       357
2       169
4       110
5        64
8        45
6        42
9        31
15       27
7        24
11       18
23       10
14        9
19        6
17        3
16        3
18        3
21        2
Name: count, dtype: int64

In [12]:
len(EA_LIB['sensor_alt'][0])

55

In [14]:
P53_LIB = pd.read_csv('/Users/kexindong/Documents/GitHub/SG-p53-prime-editing-sensor/analysis_scripts/p53_crispresso_quant.csv')

In [15]:
P53_LIB

,pegRNA_idx,impact index,gene,chr,start,end,variant_type,ref_allele,mut_allele,PAM location,...,sensor_CorrectEdit_rc,num_duplicates,duplicate_idxs,unique_proto_idx,HGVSc,HGVSp_true,peg_id,sensor_handle,wt_qwc,edit_qwc
0,0,0,TP53,chr17,7578406,7578406,SNP,C,T,7578396,...,CAGCACATGACGGAGGTTGTGAGGCACTGCCCCCACCATGAGCGCT...,1.0,[],141,c.524G>A,R175H,peg_0,CAGCAGCGAT,5-55,5-55
1,1,0,TP53,chr17,7578406,7578406,SNP,C,T,7578396,...,CAGCACATGACGGAGGTTGTGAGGCACTGCCCCCACCATGAGCGCT...,1.0,[],141,c.524G>A,R175H,peg_1,CAGCAGCGAT,5-55,5-55
2,2,0,TP53,chr17,7578406,7578406,SNP,C,T,7578410,...,GTCACAGCACATGACGGAGGTTGTGAGGCACTGCCCCCACCATGAG...,1.0,[],21,c.524G>A,R175H,peg_2,GTCACGATAG,5-55,5-55
3,3,0,TP53,chr17,7578406,7578406,SNP,C,T,7578410,...,GTCACAGCACATGACGGAGGTTGTGAGGCACTGCCCCCACCATGAG...,1.0,[],21,c.524G>A,R175H,peg_3,GTCACGATAG,5-55,5-55
4,4,0,TP53,chr17,7578406,7578406,SNP,C,T,7578410,...,GTCACAGCACATGACGGAGGTTGTGAGGCACTGCCCCCACCATGAG...,1.0,[],21,c.524G>A,R175H,peg_4,GTCACGATAG,5-55,5-55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28669,28669,1261,TP53,chr17,7572939,7572941,ONP,AGG,TGG,7572944,...,TAAAAAACTCATGTTCAAGACAGAAGGGCCAGACTCAGACTGACAT...,1.0,[],10,c.1170T>A,P390P,peg_28669,TAAAACTTGT,5-55,5-55
28670,28670,1261,TP53,chr17,7572939,7572941,ONP,AGG,TGG,7572938,...,GCCATAAAAAACTCATGTTCAAGACAGAAGGGCCAGACTCAGACTG...,1.0,[],116,c.1170T>A,P390P,peg_28670,GCCATACTTC,5-55,5-55
28671,28671,1261,TP53,chr17,7572939,7572941,ONP,AGG,TGG,7572944,...,TAAAAAACTCATGTTCAAGACAGAAGGGCCAGACTCAGACTGACAT...,1.0,[],10,c.1170T>A,P390P,peg_28671,TAAAACTTGT,5-55,5-55
28672,28672,1261,TP53,chr17,7572939,7572941,ONP,AGG,TGG,7572944,...,TAAAAAACTCATGTTCAAGACAGAAGGGCCAGACTCAGACTGACAT...,1.0,[],10,c.1170T>A,P390P,peg_28672,TAAAACTTGT,5-55,5-55
28673,28673,1261,TP53,chr17,7572939,7572941,ONP,AGG,TGG,7572944,...,TAAAAAACTCATGTTCAAGACAGAAGGGCCAGACTCAGACTGACAT...,1.0,[],10,c.1170T>A,P390P,peg_28673,TAAAACTTGT,5-55,5-55

In [17]:
len(P53_LIB['sensor_WT_rc'][0])

60

In [5]:
P53_LIB['wt_qwc'].value_counts()

wt_qwc
5-55    28659
5-50        9
5-53        6
Name: count, dtype: int64

In [6]:
P53_LIB['edit_qwc'].value_counts()

edit_qwc
5-55    22655
5-54     2576
5-56     1329
5-57      364
5-58      282
5-53      254
5-52      231
5-60      182
5-59      123
5-61      115
5-64       72
5-49       68
5-62       64
5-51       57
5-46       38
5-42       33
5-69       33
5-63       30
5-70       30
5-67       30
5-43       24
5-45       21
5-76       12
5-50        9
5-39        9
5-47        9
5-37        6
5-66        6
5-75        3
5-38        3
5-48        3
5-74        3
Name: count, dtype: int64

In [7]:
P53_LIB[P53_LIB['edit_qwc']=='5-58']

,pegRNA_idx,impact index,gene,chr,start,end,variant_type,ref_allele,mut_allele,PAM location,...,sensor_CorrectEdit_rc,num_duplicates,duplicate_idxs,unique_proto_idx,HGVSc,HGVSp_true,peg_id,sensor_handle,wt_qwc,edit_qwc
20591,20591,890,TP53,chr17,7579358,7579359,INS,-,TTT,7579366,...,CCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGAAATCTGGGCTT...,1.0,[],1,c.329_330insAAA,R110_L111insN,peg_20591,CCCAGGACAG,5-55,5-58
20592,20592,890,TP53,chr17,7579358,7579359,INS,-,TTT,7579355,...,TACCAGGGCAGCTACGGTTTCCGAAATCTGGGCTTCTTGCATTCTG...,1.0,[],125,c.329_330insAAA,R110_L111insN,peg_20592,TACCACTGTG,5-55,5-58
20593,20593,890,TP53,chr17,7579358,7579359,INS,-,TTT,7579355,...,TACCAGGGCAGCTACGGTTTCCGAAATCTGGGCTTCTTGCATTCTG...,1.0,[],125,c.329_330insAAA,R110_L111insN,peg_20593,TACCACTGTG,5-55,5-58
20594,20594,890,TP53,chr17,7579358,7579359,INS,-,TTT,7579355,...,TACCAGGGCAGCTACGGTTTCCGAAATCTGGGCTTCTTGCATTCTG...,1.0,[],125,c.329_330insAAA,R110_L111insN,peg_20594,TACCACTGTG,5-55,5-58
20595,20595,890,TP53,chr17,7579358,7579359,INS,-,TTT,7579355,...,TACCAGGGCAGCTACGGTTTCCGAAATCTGGGCTTCTTGCATTCTG...,1.0,[],125,c.329_330insAAA,R110_L111insN,peg_20595,TACCACTGTG,5-55,5-58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22760,22760,987,TP53,chr17,7578457,7578458,INS,-,GGA,7578471,...,TGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGTCCCGC...,1.0,[],137,c.473_474insTCC,R158_A159insP,peg_22760,TGTGGCAAGC,5-55,5-58
22761,22761,987,TP53,chr17,7578457,7578458,INS,-,GGA,7578451,...,TTCCACACCCCCGCCCGGCACCCGCGTCCGTCCCGCCATGGCCATC...,1.0,[],156,c.473_474insTCC,R158_A159insP,peg_22761,TTCCACAGCA,5-55,5-58
22762,22762,987,TP53,chr17,7578457,7578458,INS,-,GGA,7578451,...,TTCCACACCCCCGCCCGGCACCCGCGTCCGTCCCGCCATGGCCATC...,1.0,[],156,c.473_474insTCC,R158_A159insP,peg_22762,TTCCACAGCA,5-55,5-58
22763,22763,987,TP53,chr17,7578457,7578458,INS,-,GGA,7578451,...,TTCCACACCCCCGCCCGGCACCCGCGTCCGTCCCGCCATGGCCATC...,1.0,[],156,c.473_474insTCC,R158_A159insP,peg_22763,TTCCACAGCA,5-55,5-58
22764,22764,987,TP53,chr17,7578457,7578458,INS,-,GGA,7578456,...,GTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGTCCCGCCATGG...,1.0,[],115,c.473_474insTCC,R158_A159insP,peg_22764,GTTGAAGTCA,5-55,5-58

For generation of the editing window of PE, for now, take [5:-5] of the sensor sequence and adjust it based on the indel size.

In [18]:
sensor_len = 55

In [24]:
EA_LIB['indel_size'].value_counts()

indel_size
0     27919
1      1318
3       357
2       169
4       110
5        64
8        45
6        42
9        31
15       27
7        24
11       18
23       10
14        9
19        6
17        3
16        3
18        3
21        2
Name: count, dtype: int64

In [20]:
EA_LIB['wt_qwc'] = '5-50'

In [73]:
def get_edit_wc(row):
    ref_seq_m = row['ref_seq_m_ori']
    alt_seq_m = row['alt_seq_m_ori']
    variant_type = row['Variant_Type']
    indel_size = row['indel_size']
    if (indel_size == 0) or (len(ref_seq_m) == len(alt_seq_m)):
        edit_qwc = '5-50'
    else:
        end_coor = 50 - len(ref_seq_m) + len(alt_seq_m)
        edit_qwc = f'5-{str(end_coor)}'

    return edit_qwc

In [74]:
get_edit_wc(EA_LIB.iloc[0,:])

'5-50'

In [75]:
EA_LIB[EA_LIB['Variant_Type']=='INS'][['indel_size','HGVSc_h']]

       indel_size                                  HGVSc_h
728             9  ENST00000373344.5:c.4388_4389>AGAGGAGGA
729             9  ENST00000373344.5:c.4388_4389>AGAGGAGGA
730             9  ENST00000373344.5:c.4388_4389>AGAGGAGGA
731             9  ENST00000373344.5:c.4388_4389>AGAGGAGGA
732             9  ENST00000373344.5:c.4388_4389>AGAGGAGGA
...           ...                                      ...
25582           1          ENST00000268489.5:c.9252_9253>T
25583           1          ENST00000268489.5:c.9252_9253>T
25584           1          ENST00000268489.5:c.9252_9253>T
25585           1          ENST00000268489.5:c.9252_9253>T
25586           1          ENST00000268489.5:c.9252_9253>T

[536 rows x 2 columns]

In [76]:
EA_LIB['edit_qwc'] = EA_LIB.apply(get_edit_wc, axis=1)
EA_LIB['edit_qwc'].value_counts()

edit_qwc
5-50    29228
5-48      249
5-52      138
5-49       88
5-47       68
5-51       60
5-54       60
5-44       42
5-43       39
5-46       35
5-45       24
5-36       24
5-42       22
5-40       18
5-55       11
5-58        9
5-28        9
5-37        9
5-57        6
5-34        6
5-32        6
5-35        3
5-33        3
5-30        2
5-27        1
Name: count, dtype: int64

In [77]:
EA_LIB.to_csv('pegRNA_library_EA_LUAD_column_renamed_qwc.csv', index=False)