## 02_generate_config_file
This script generates a config file for NGS data processing.  

Update: Nov 25, 2025  
Generate config file for the validation library of B-ALL in vivo screen.

In [2]:
import numpy as np 
import pandas as pd
import os

## SENSOR EXTRACTION

### STEP 1:  Generate config file.

In [ ]:
#connect to the server and copy the path to your sequencing data
fp = '/Volumes/sanchezrivera/kexindong/250730Hem'
k = os.listdir(fp)

#might need to change the 'D24' depending on file naming
k = [i for i in k if i[:3]=='D25'] 

folder_name = []
f1 = []
f2 = []
for ii in range(len(k)):
    j = os.listdir(f'{fp}/{k[ii]}')
    j = sorted([i for i in j if i[-5:]=='fastq'])

    #weird error to deal with
    #hacky solution
    if len(j)==2:
        f1.append(f'./{k[ii]}/{j[0]}')
        f2.append(f'./{k[ii]}/{j[1]}')
    else:
        f1.append(f'./{k[ii]}/{j[2]}')
        f2.append(f'./{k[ii]}/{j[3]}')
    folder_name.append(k[ii] + '_guide_split_BARCODES')

config_df = pd.DataFrame(dict(zip(['ArrayTaskID', 'R1_FILE', 'R2_FILE', 'folder_name'], [list(range(1, len(f1)+1)), f1, f2, folder_name])))
#config_df.to_csv('sensor_extraction_fastq_split_config_DIEGO_IDR.txt', index=False, sep = ' ')
config_df

,ArrayTaskID,R1_FILE,R2_FILE,folder_name
0,1,./D25-13245-1-7331E/251030Hem_D25-13245-1_1_se...,./D25-13245-1-7331E/251030Hem_D25-13245-1_2_se...,D25-13245-1-7331E_guide_split_BARCODES
1,2,./D25-13245-2-7331E/251030Hem_D25-13245-2_1_se...,./D25-13245-2-7331E/251030Hem_D25-13245-2_2_se...,D25-13245-2-7331E_guide_split_BARCODES
2,3,./D25-13246-1-7331E/251030Hem_D25-13246-1_1_se...,./D25-13246-1-7331E/251030Hem_D25-13246-1_2_se...,D25-13246-1-7331E_guide_split_BARCODES
3,4,./D25-13246-2-7331E/251030Hem_D25-13246-2_1_se...,./D25-13246-2-7331E/251030Hem_D25-13246-2_2_se...,D25-13246-2-7331E_guide_split_BARCODES
4,5,./D25-13247-1-7331E/251030Hem_D25-13247-1_1_se...,./D25-13247-1-7331E/251030Hem_D25-13247-1_2_se...,D25-13247-1-7331E_guide_split_BARCODES
...,...,...,...,...
183,184,./D25-13795-2-7331E/251030Hem_D25-13795-2_1_se...,./D25-13795-2-7331E/251030Hem_D25-13795-2_2_se...,D25-13795-2-7331E_guide_split_BARCODES
184,185,./D25-13796-1-7331E/251030Hem_D25-13796-1_1_se...,./D25-13796-1-7331E/251030Hem_D25-13796-1_2_se...,D25-13796-1-7331E_guide_split_BARCODES
185,186,./D25-13796-2-7331E/251030Hem_D25-13796-2_1_se...,./D25-13796-2-7331E/251030Hem_D25-13796-2_2_se...,D25-13796-2-7331E_guide_split_BARCODES
186,187,./D25-13797-1-7331E/251030Hem_D25-13797-1_1_se...,./D25-13797-1-7331E/251030Hem_D25-13797-1_2_se...,D25-13797-1-7331E_guide_split_BARCODES
187,188,./D25-13797-2-7331E/251030Hem_D25-13797-2_1_se...,./D25-13797-2-7331E/251030Hem_D25-13797-2_2_se...,D25-13797-2-7331E_guide_split_BARCODES

In [5]:
config_df.to_csv('sensor_extraction_fastq_split_config_EA_JA.txt', index=False, sep = ' ')

### STEP 2:  Generate Library File.

In [6]:
EA_LIB = pd.read_csv('/Users/kexindong/Documents/GitHub/SG-EA-LUAD-Prime-Editing/pegRNA_library_EA_LUAD.csv')
EA_LIB

,mutation_idx,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,...,pegRNA_rank,sensor_wt,sensor_alt,sensor_orientation,sensor_error,contains_polyT_terminator,pegRNA_id,pegRNA_oligo,num_RE_sites,barcode
0,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,1.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_1,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAAAC
1,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,2.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_2,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAAAG
2,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,3.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_3,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACA
3,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,4.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_4,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACC
4,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,5.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_5,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30155,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,11.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30156,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCA
30156,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,12.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30157,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCC
30157,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,13.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30158,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCG
30158,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,14.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30159,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCT
30159,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,15.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30160,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATGA

In [7]:
required = ['gRNA_id','Protospacer','Hamming_BC','sensor_wt','sensor_alt']
mask = pd.Index(required).isin(EA_LIB.columns)
print(mask)

[False  True False  True  True]

In [8]:
EA_LIB.columns

Index(['mutation_idx', 'gene_name_h', 'gene_id_h', 'tx_id_h', 'chr_h',
       'exon_num_h', 'strand_h', 'match', 'start_h', 'end_h', 'ref_seq_h',
       'alt_seq_h', 'HGVSc_h', 'HGVSp_h', 'classification_h', 'exon_h',
       'type_h', 'status', 'class', 'statement', 'flank_size_left',
       'flank_size_right', 'gene_name_m', 'gene_id_m', 'tx_id_m', 'Chromosome',
       'exon_num_m', 'strand_m', 'Variant_Type', 'classification_m', 'exon_m',
       'start_m_ori', 'end_m_ori', 'ref_seq_m_ori', 'alt_seq_m_ori',
       'HGVSc_m_ori', 'HGVSp_m_ori', 'Start_Position', 'End_Position',
       'Reference_Allele', 'Tumor_Seq_Allele2', 'HGVSc_m', 'HGVSp_m',
       'ID_human', 'ID_mouse', 'Database', 'ID_db', 'pe_human', 'pe_mouse',
       'be_human', 'be_mouse', 'expanded', 'flank_size', 'seq_start',
       'seq_end', 'wt_w_context', 'alt_w_context', 'left_context',
       'right_context', 'REF', 'ALT', 'PAM_start', 'PAM_end', 'PAM',
       'PAM_strand', 'Protospacer_30', 'Protospacer', 'RTT', 'RTT_length',
       'PBS', 'PBS_length', 'RTT_PBS', 'Distance_to_nick', 'RHA_size',
       'PAM_disrupted', 'Proto_disrupted', 'OnTarget_Azimuth_Score',
       'PBS_GC_content', 'RTT_GC_content', 'indel_size', 'PEGG2_Score',
       'RF_Score', 'pegRNA_rank', 'sensor_wt', 'sensor_alt',
       'sensor_orientation', 'sensor_error', 'contains_polyT_terminator',
       'pegRNA_id', 'pegRNA_oligo', 'num_RE_sites', 'barcode'],
      dtype='object')

In [9]:
EA_LIB = EA_LIB.rename(columns={'barcode':'Hamming_BC'})
EA_LIB.columns

Index(['mutation_idx', 'gene_name_h', 'gene_id_h', 'tx_id_h', 'chr_h',
       'exon_num_h', 'strand_h', 'match', 'start_h', 'end_h', 'ref_seq_h',
       'alt_seq_h', 'HGVSc_h', 'HGVSp_h', 'classification_h', 'exon_h',
       'type_h', 'status', 'class', 'statement', 'flank_size_left',
       'flank_size_right', 'gene_name_m', 'gene_id_m', 'tx_id_m', 'Chromosome',
       'exon_num_m', 'strand_m', 'Variant_Type', 'classification_m', 'exon_m',
       'start_m_ori', 'end_m_ori', 'ref_seq_m_ori', 'alt_seq_m_ori',
       'HGVSc_m_ori', 'HGVSp_m_ori', 'Start_Position', 'End_Position',
       'Reference_Allele', 'Tumor_Seq_Allele2', 'HGVSc_m', 'HGVSp_m',
       'ID_human', 'ID_mouse', 'Database', 'ID_db', 'pe_human', 'pe_mouse',
       'be_human', 'be_mouse', 'expanded', 'flank_size', 'seq_start',
       'seq_end', 'wt_w_context', 'alt_w_context', 'left_context',
       'right_context', 'REF', 'ALT', 'PAM_start', 'PAM_end', 'PAM',
       'PAM_strand', 'Protospacer_30', 'Protospacer', 'RTT', 'RTT_length',
       'PBS', 'PBS_length', 'RTT_PBS', 'Distance_to_nick', 'RHA_size',
       'PAM_disrupted', 'Proto_disrupted', 'OnTarget_Azimuth_Score',
       'PBS_GC_content', 'RTT_GC_content', 'indel_size', 'PEGG2_Score',
       'RF_Score', 'pegRNA_rank', 'sensor_wt', 'sensor_alt',
       'sensor_orientation', 'sensor_error', 'contains_polyT_terminator',
       'pegRNA_id', 'pegRNA_oligo', 'num_RE_sites', 'Hamming_BC'],
      dtype='object')

In [12]:
EA_LIB.to_csv('pegRNA_library_EA_LUAD_column_renamed.csv', index = False)

### STEP 3: Add the files to the sequencing data folder.

### STEP 4: MAKE 4 FOLDERS WITHIN THE SEQUENCING FOLDER. THE NAMES MUST BE EXACT (no capital letters):
- classification
- confusion_mats
- counts
- crispresso

### STEP 5: Get the length of BC and SENSOR.

In [16]:
[len(x) for x in EA_LIB['sensor_wt']]

[55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 ...]

In [17]:
[len(x) for x in EA_LIB['Hamming_BC']]

[8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 ...]

# Update - Generate config file for rerunning the EA library with extended barcode.

### STEP 1:  Generate config file.

In [28]:
#connect to the server and copy the path to your sequencing data
fp = '/Volumes/sanchezrivera/kexindong/250730Hem'
k = os.listdir(fp)
#might need to change the 'D24' depending on file naming
k = [i for i in k if i[:3]=='D25' and len(i)==17]
len(k)
folder_name = []
f1 = []
f2 = []
for ii in range(len(k)):
    j = os.listdir(f'{fp}/{k[ii]}')
    j = sorted([i for i in j if i[-5:]=='fastq'])

    #weird error to deal with
    #hacky solution
    if len(j)==2:
        f1.append(f'./{k[ii]}/{j[0]}')
        f2.append(f'./{k[ii]}/{j[1]}')
    else:
        f1.append(f'./{k[ii]}/{j[2]}')
        f2.append(f'./{k[ii]}/{j[3]}')
    folder_name.append(f'./extended_bc_16nt_analysis/{k[ii]}_guide_split_BARCODES')

config_df = pd.DataFrame(dict(zip(['ArrayTaskID', 'R1_FILE', 'R2_FILE', 'folder_name'], [list(range(1, len(f1)+1)), f1, f2, folder_name])))
#config_df.to_csv('sensor_extraction_fastq_split_config_DIEGO_IDR.txt', index=False, sep = ' ')
config_df

,ArrayTaskID,R1_FILE,R2_FILE,folder_name
0,1,./D25-10052-1-7225E/250730Hem_D25-10052-1_1_se...,./D25-10052-1-7225E/250730Hem_D25-10052-1_2_se...,./extended_bc_16nt_analysis/D25-10052-1-7225E_...
1,2,./D25-10052-2-7225E/250730Hem_D25-10052-2_1_se...,./D25-10052-2-7225E/250730Hem_D25-10052-2_2_se...,./extended_bc_16nt_analysis/D25-10052-2-7225E_...
2,3,./D25-10053-1-7225E/250730Hem_D25-10053-1_1_se...,./D25-10053-1-7225E/250730Hem_D25-10053-1_2_se...,./extended_bc_16nt_analysis/D25-10053-1-7225E_...
3,4,./D25-10053-2-7225E/250730Hem_D25-10053-2_1_se...,./D25-10053-2-7225E/250730Hem_D25-10053-2_2_se...,./extended_bc_16nt_analysis/D25-10053-2-7225E_...
4,5,./D25-10054-1-7225E/250730Hem_D25-10054-1_1_se...,./D25-10054-1-7225E/250730Hem_D25-10054-1_2_se...,./extended_bc_16nt_analysis/D25-10054-1-7225E_...
5,6,./D25-10054-2-7225E/250730Hem_D25-10054-2_1_se...,./D25-10054-2-7225E/250730Hem_D25-10054-2_2_se...,./extended_bc_16nt_analysis/D25-10054-2-7225E_...
6,7,./D25-10055-1-7225E/250730Hem_D25-10055-1_1_se...,./D25-10055-1-7225E/250730Hem_D25-10055-1_2_se...,./extended_bc_16nt_analysis/D25-10055-1-7225E_...
7,8,./D25-10055-2-7225E/250730Hem_D25-10055-2_1_se...,./D25-10055-2-7225E/250730Hem_D25-10055-2_2_se...,./extended_bc_16nt_analysis/D25-10055-2-7225E_...
8,9,./D25-10056-1-7225E/250730Hem_D25-10056-1_1_se...,./D25-10056-1-7225E/250730Hem_D25-10056-1_2_se...,./extended_bc_16nt_analysis/D25-10056-1-7225E_...
9,10,./D25-10056-2-7225E/250730Hem_D25-10056-2_1_se...,./D25-10056-2-7225E/250730Hem_D25-10056-2_2_se...,./extended_bc_16nt_analysis/D25-10056-2-7225E_...
10,11,./D25-10057-1-7225E/250730Hem_D25-10057-1_1_se...,./D25-10057-1-7225E/250730Hem_D25-10057-1_2_se...,./extended_bc_16nt_analysis/D25-10057-1-7225E_...
11,12,./D25-10057-2-7225E/250730Hem_D25-10057-2_1_se...,./D25-10057-2-7225E/250730Hem_D25-10057-2_2_se...,./extended_bc_16nt_analysis/D25-10057-2-7225E_...
12,13,./D25-10058-1-7225E/250730Hem_D25-10058-1_1_se...,./D25-10058-1-7225E/250730Hem_D25-10058-1_2_se...,./extended_bc_16nt_analysis/D25-10058-1-7225E_...
13,14,./D25-10058-2-7225E/250730Hem_D25-10058-2_1_se...,./D25-10058-2-7225E/250730Hem_D25-10058-2_2_se...,./extended_bc_16nt_analysis/D25-10058-2-7225E_...
14,15,./D25-10059-1-7225E/250730Hem_D25-10059-1_1_se...,./D25-10059-1-7225E/250730Hem_D25-10059-1_2_se...,./extended_bc_16nt_analysis/D25-10059-1-7225E_...
15,16,./D25-10059-2-7225E/250730Hem_D25-10059-2_1_se...,./D25-10059-2-7225E/250730Hem_D25-10059-2_2_se...,./extended_bc_16nt_analysis/D25-10059-2-7225E_...
16,17,./D25-10060-1-7225E/250730Hem_D25-10060-1_1_se...,./D25-10060-1-7225E/250730Hem_D25-10060-1_2_se...,./extended_bc_16nt_analysis/D25-10060-1-7225E_...
17,18,./D25-10060-2-7225E/250730Hem_D25-10060-2_1_se...,./D25-10060-2-7225E/250730Hem_D25-10060-2_2_se...,./extended_bc_16nt_analysis/D25-10060-2-7225E_...
18,19,./D25-10061-1-7225E/250730Hem_D25-10061-1_1_se...,./D25-10061-1-7225E/250730Hem_D25-10061-1_2_se...,./extended_bc_16nt_analysis/D25-10061-1-7225E_...
19,20,./D25-10061-2-7225E/250730Hem_D25-10061-2_1_se...,./D25-10061-2-7225E/250730Hem_D25-10061-2_2_se...,./extended_bc_16nt_analysis/D25-10061-2-7225E_...
20,21,./D25-10062-1-7225E/250730Hem_D25-10062-1_1_se...,./D25-10062-1-7225E/250730Hem_D25-10062-1_2_se...,./extended_bc_16nt_analysis/D25-10062-1-7225E_...
21,22,./D25-10062-2-7225E/250730Hem_D25-10062-2_1_se...,./D25-10062-2-7225E/250730Hem_D25-10062-2_2_se...,./extended_bc_16nt_analysis/D25-10062-2-7225E_...
22,23,./D25-10063-1-7225E/250730Hem_D25-10063-1_1_se...,./D25-10063-1-7225E/250730Hem_D25-10063-1_2_se...,./extended_bc_16nt_analysis/D25-10063-1-7225E_...
23,24,./D25-10063-2-7225E/250730Hem_D25-10063-2_1_se...,./D25-10063-2-7225E/250730Hem_D25-10063-2_2_se...,./extended_bc_16nt_analysis/D25-10063-2-7225E_...
24,25,./D25-10064-1-7225E/250730Hem_D25-10064-1_1_se...,./D25-10064-1-7225E/250730Hem_D25-10064-1_2_se...,./extended_bc_16nt_analysis/D25-10064-1-7225E_...
25,26,./D25-10064-2-7225E/250730Hem_D25-10064-2_1_se...,./D25-10064-2-7225E/250730Hem_D25-10064-2_2_se...,./extended_bc_16nt_analysis/D25-10064-2-7225E_...
26,27,./D25-10065-1-7225E/250730Hem_D25-10065-1_1_se...,./D25-10065-1-7225E/250730Hem_D25-10065-1_2_se...,./extended_bc_16nt_analysis/D25-10065-1-7225E_...
27,28,./D25-10065-2-7225E/250730Hem_D25-10065-2_1_se...,./D25-10065-2-7225E/250730Hem_D25-10065-2_2_se...,./extended_bc_16nt_analysis/D25-10065-2-7225E_...
28,29,./D25-10066-1-7225E/250730Hem_D25-10066-1_1_se...,./D25-10066-1-7225E/250730Hem_D25-10066-1_2_se...,./extended_bc_16nt_analysis/D25-10066-1-7225E_...
29,30,./D25-10066-2-7225E/250730Hem_D25-10066-2_1_se...,./D25-10066-2-7225E/250730Hem_D25-10066-2_2_se...,./extended_bc_16nt_analysis/D25-10066-2-7225E_...
30,31,./D25-10067-1-7225E/250730Hem_D25-10067-1_1_se...,./D25-10067-1-7225E/250730Hem_D25-10067-1_2_se...,./extended_bc_16nt_analysis/D25-10067-1-7225E_...
31,32,./D25-10067-2-7225E/250730Hem_D25-10067-2_1_se...,./D25-10067-2-7225E/250730Hem_D25-10067-2_2_se...,./extended_bc_16nt_analysis/D25-10067-2-7225E_...

In [29]:
config_df.to_csv('CONFIG_EA_JA_SENSOR_EXTRACTION_BC_16NT.txt', index=False, sep = ' ')

### STEP 2:  Generate Library File.

In [30]:
EA_LIB = pd.read_csv('/Users/kexindong/Documents/GitHub/SG-EA-LUAD-Prime-Editing/pegRNA_library_EA_LUAD.csv')
EA_LIB

,mutation_idx,gene_name_h,gene_id_h,tx_id_h,chr_h,exon_num_h,strand_h,match,start_h,end_h,...,pegRNA_rank,sensor_wt,sensor_alt,sensor_orientation,sensor_error,contains_polyT_terminator,pegRNA_id,pegRNA_oligo,num_RE_sites,barcode
0,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,1.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_1,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAAAC
1,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,2.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_2,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAAAG
2,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,3.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_3,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACA
3,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,4.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_4,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACC
4,0,CHEK2,ENSG00000183765.16,ENST00000382580.2,chr22,15,-,True,29092948,29092948,...,5.0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,No Error,False,pegRNA_5,AGCGTACACGTCTCACACCGGAAAATGGGATCATACATCGTTTAAG...,2,AAACAACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30155,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,11.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30156,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCA
30156,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,12.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30157,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCC
30157,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,13.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30158,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCG
30158,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,14.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30159,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATCT
30159,1393,DIS3,ENSG00000083520.10,ENST00000377767.4,chr13,21,-,True,73346015,73346015,...,15.0,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,No Error,False,pegRNA_30160,AGCGTACACGTCTCACACCGAAGGTTGGTGTTCATATTGGTTTAAG...,2,GTCGATGA

In [31]:
required = ['gRNA_id','Protospacer','Hamming_BC','sensor_wt','sensor_alt']
mask = pd.Index(required).isin(EA_LIB.columns)
print(mask)

[False  True False  True  True]

In [32]:
EA_LIB.columns

Index(['mutation_idx', 'gene_name_h', 'gene_id_h', 'tx_id_h', 'chr_h',
       'exon_num_h', 'strand_h', 'match', 'start_h', 'end_h', 'ref_seq_h',
       'alt_seq_h', 'HGVSc_h', 'HGVSp_h', 'classification_h', 'exon_h',
       'type_h', 'status', 'class', 'statement', 'flank_size_left',
       'flank_size_right', 'gene_name_m', 'gene_id_m', 'tx_id_m', 'Chromosome',
       'exon_num_m', 'strand_m', 'Variant_Type', 'classification_m', 'exon_m',
       'start_m_ori', 'end_m_ori', 'ref_seq_m_ori', 'alt_seq_m_ori',
       'HGVSc_m_ori', 'HGVSp_m_ori', 'Start_Position', 'End_Position',
       'Reference_Allele', 'Tumor_Seq_Allele2', 'HGVSc_m', 'HGVSp_m',
       'ID_human', 'ID_mouse', 'Database', 'ID_db', 'pe_human', 'pe_mouse',
       'be_human', 'be_mouse', 'expanded', 'flank_size', 'seq_start',
       'seq_end', 'wt_w_context', 'alt_w_context', 'left_context',
       'right_context', 'REF', 'ALT', 'PAM_start', 'PAM_end', 'PAM',
       'PAM_strand', 'Protospacer_30', 'Protospacer', 'RTT', 'RTT_length',
       'PBS', 'PBS_length', 'RTT_PBS', 'Distance_to_nick', 'RHA_size',
       'PAM_disrupted', 'Proto_disrupted', 'OnTarget_Azimuth_Score',
       'PBS_GC_content', 'RTT_GC_content', 'indel_size', 'PEGG2_Score',
       'RF_Score', 'pegRNA_rank', 'sensor_wt', 'sensor_alt',
       'sensor_orientation', 'sensor_error', 'contains_polyT_terminator',
       'pegRNA_id', 'pegRNA_oligo', 'num_RE_sites', 'barcode'],
      dtype='object')

In [33]:
EA_LIB = EA_LIB.rename(columns={'barcode':'Hamming_BC'})
EA_LIB.columns

Index(['mutation_idx', 'gene_name_h', 'gene_id_h', 'tx_id_h', 'chr_h',
       'exon_num_h', 'strand_h', 'match', 'start_h', 'end_h', 'ref_seq_h',
       'alt_seq_h', 'HGVSc_h', 'HGVSp_h', 'classification_h', 'exon_h',
       'type_h', 'status', 'class', 'statement', 'flank_size_left',
       'flank_size_right', 'gene_name_m', 'gene_id_m', 'tx_id_m', 'Chromosome',
       'exon_num_m', 'strand_m', 'Variant_Type', 'classification_m', 'exon_m',
       'start_m_ori', 'end_m_ori', 'ref_seq_m_ori', 'alt_seq_m_ori',
       'HGVSc_m_ori', 'HGVSp_m_ori', 'Start_Position', 'End_Position',
       'Reference_Allele', 'Tumor_Seq_Allele2', 'HGVSc_m', 'HGVSp_m',
       'ID_human', 'ID_mouse', 'Database', 'ID_db', 'pe_human', 'pe_mouse',
       'be_human', 'be_mouse', 'expanded', 'flank_size', 'seq_start',
       'seq_end', 'wt_w_context', 'alt_w_context', 'left_context',
       'right_context', 'REF', 'ALT', 'PAM_start', 'PAM_end', 'PAM',
       'PAM_strand', 'Protospacer_30', 'Protospacer', 'RTT', 'RTT_length',
       'PBS', 'PBS_length', 'RTT_PBS', 'Distance_to_nick', 'RHA_size',
       'PAM_disrupted', 'Proto_disrupted', 'OnTarget_Azimuth_Score',
       'PBS_GC_content', 'RTT_GC_content', 'indel_size', 'PEGG2_Score',
       'RF_Score', 'pegRNA_rank', 'sensor_wt', 'sensor_alt',
       'sensor_orientation', 'sensor_error', 'contains_polyT_terminator',
       'pegRNA_id', 'pegRNA_oligo', 'num_RE_sites', 'Hamming_BC'],
      dtype='object')

In [35]:
import pegg.prime as prime

/Users/kexindong/Library/Python/3.9/lib/python/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(

In [36]:
prime.prime_oligo_generator

<function pegg.prime.prime_oligo_generator(peg_df, epeg=True, epeg_motif='tevopreQ1', five_prime_adapter='AGCGTACACGTCTCACACC', three_prime_adapter='GAATTCTAGATCCGGTCGTCAAC', gRNA_scaff='GTTTTAGAGCTAGAAATAGCAAGTTAAAATAAGGCTAGTCCGTTATCAACTTGAAAAAGTGGCACCGAGTCGGTGC')>

In [34]:
EA_LIB[['sensor_wt', 'sensor_alt',
       'sensor_orientation','Hamming_BC']]

,sensor_wt,sensor_alt,sensor_orientation,Hamming_BC
0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,AAACAAAC
1,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,AAACAAAG
2,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,AAACAACA
3,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,AAACAACC
4,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,AAACAACT
...,...,...,...,...
30155,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,GTCGATCA
30156,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,GTCGATCC
30157,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,GTCGATCG
30158,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,GTCGATCT
30159,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,GTCGATGA

In [44]:
EA_LIB_BC_16NT = EA_LIB.copy()
hamming_BC_16_NT = []
for idx, row in EA_LIB.iterrows():
	hamming_BC_16_NT.append(row['sensor_wt'][-8:]+row['Hamming_BC'])
EA_LIB_BC_16NT['Hamming_BC'] = hamming_BC_16_NT
EA_LIB_BC_16NT[['sensor_wt', 'sensor_alt',
       'sensor_orientation','Hamming_BC']]

,sensor_wt,sensor_alt,sensor_orientation,Hamming_BC
0,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,TCGTGAAGAAACAAAC
1,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,TCGTGAAGAAACAAAG
2,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,TCGTGAAGAAACAACA
3,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,TCGTGAAGAAACAACC
4,ATAAAAGAACATTCTCCGGCTTTAAGTCCCGATGTATGATCCCATT...,ATAAAAGAACATTCTCCGGCTTTAAGTCACAATGTATGATCCCATT...,reverse-complement,TCGTGAAGAAACAACT
...,...,...,...,...
30155,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,TTAAAAAGGTCGATCA
30156,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,TTAAAAAGGTCGATCC
30157,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,TTAAAAAGGTCGATCG
30158,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,TTAAAAAGGTCGATCT
30159,TTCCTGGCCTGATAAAATGGCTAACATCCGCAATATGAACACCAAC...,TTCCTGGCCTGATAAAATGGCTAACACCCGCAATATGAACACCAAC...,reverse-complement,TTAAAAAGGTCGATGA

In [39]:
'./extended_bc_16nt_analysis/D25-10061-2-7225E_guide_split_BARCODES'.split('/')[-1]

'D25-10061-2-7225E_guide_split_BARCODES'

In [45]:
EA_LIB_BC_16NT.to_csv('pegRNA_library_EA_LUAD_column_renamed_bc_16nt.csv', index = False)

### STEP 3: Add the files to the sequencing data folder.

### STEP 4: MAKE 4 FOLDERS WITHIN THE SEQUENCING FOLDER. THE NAMES MUST BE EXACT (no capital letters):
- classification
- confusion_mats
- counts
- crispresso

### STEP 5: Get the length of BC and SENSOR.

In [ ]:
[len(x) for x in EA_LIB['sensor_wt']]

[55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 55,
 ...]

In [ ]:
[len(x) for x in EA_LIB['Hamming_BC']]

[8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 ...]

## SENSOR ANALYSIS - CRISPRESSO

### STEP 6: Get editing window coordinates for crispresso analysis according to indel size.